# Generated by Django 5.2.3 on 2025-06-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='slug',
        ),
    ]
