# Generated by Django 5.2.3 on 2025-06-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultora', '0002_remove_categoria_slug_remove_curso_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='empresa',
        ),
    ]
